[package]
name = "project_1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.20", features = ["derive"] }
